language: php
php:
 - 5.6
 - 7.0


before_install:
  - sudo apt-get update -qq

install:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction

before_script:
  # set up app
script:
  - php ./vendor/bin/phpunit --colors --configuration ./phpunit.xml --coverage-clover=./reports/coverage/clover.xml

after_script:
  - php ./vendor/bin/coveralls -v
